### ISSUE TITLE
needs an update

### ISSUE THREAD

**Issue by aamorous** [MIMJA156/time-tracker#6]
hey, man really love your extension, it stoped working since 1.82 update, doesn't show time, it shows text only when idling

**Comment by MIMJA156** [comment]
Thanks for letting me know and I'm glad you like my little extension!

I just checked the extension and it seems to be working fine. The time shows up in the status bar and on the web. Could you please elaborate on what the issue is? Possibly including more information such as screenshots or possible crash logs? (if you can even get those from vscode)

This is my first real issue from a user so bare with me!

**Comment by aamorous** [comment]
![Screenshot 2023-10-24 123323](https://github.com/MIMJA156/time-tracker/assets/137004870/7afda6fe-2418-47ec-959f-8a0b065a31e0)

![Screenshot 2023-10-24 123436](https://github.com/MIMJA156/time-tracker/assets/137004870/7c445196-ffec-4c56-a9b9-e0b1daae2176)


Eh, tried to enable today, seems still doesn't work..

**Comment by aamorous** [comment]
only works label "idle" when 60 mins pass

in user settings:
"mimjas-time-tracker.timeTillIdle": 60,
 "mimjas-time-tracker.iconStyle": "zap",

**Comment by aamorous** [comment]
![image](https://github.com/MIMJA156/time-tracker/assets/137004870/828714ae-76d7-4559-a46c-05af37ca1536)
It works!! had to reinstall windows and that worked
